version: '3.7'

services:
  app_api:
    build: .
    image: app_node_ts
    container_name: app_api
    restart: always
    ports:
      - '3333:3333'
    volumes:
      - ./logs:/usr/src/app/logs:rw
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - app_pgsql
  app_pgsql:
    image: postgres
    container_name: 'app_pgsql'
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - TYPEORM_USERNAME=$TYPEORM_USERNAME
      - TYPEORM_PASSWORD=$TYPEORM_PASSWORD
      - TYPEORM_DATABASE=$TYPEORM_DATABASE
    ports:
      - '5432:5432'

  app_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"

volumes:
  api-logs:
  db:
